remote_theme: vsanthanam/jekyll-docs-theme
# show_downloads: true
name: VSAlert

project:
    version: 1.3.1
    download_url: https://www.github.com/vsanthanam/VSAlert/releases

license:
    software: MIT License
    software_url: http://opensource.org/licenses/MIT

    docs: CC BY 3.0
    docs_url: http://creativecommons.org/licenses/by/3.0/

links:
    header:
      - title: GitHub
        url: https://www.github.com/vsanthanam/VSAlert
      - title: Documentation
        url: https://code.vsanthanam.com/VSAlert/Documentation/index.html
    footer:
      - title: GitHub
        url: https://www.github.com/vsanthanam/VSAlert/jekyll-docs-theme
      - title: Issues
        url: https://www.github.com/vsanthanam/VSAlert/issues?state=open

ui:
    header:
        color1: "#80D0C7"
        color2: "#13547A"
        trianglify: true

social:
    github:
        user: vsanthanam
        repo: VSAlert
    twitter:
        enabled: false
        via:
        hash:
        account: 
    facebook:
        enabled: false
        profileUrl:

# Build settings
markdown: kramdown
exclude:
    - Gemfile
    - Gemfile.lock